name: frontend
description: "Frontend for CGI flight app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  cached_network_image: ^3.3.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/images/cities/